### PR TITLE
Upload page redesigned and re implemented 

### PR DESCRIPTION
**Pull request by tewarig**
This pr solves #33 
as discuss this pr adds 

- [x] sidebar for navigation (animated)
- [x] separate upload button
- [x] own image gallery (responsive)
- [x] click to zoom feature (single click to zoom in and zoom out)
- [x] new updated image gallery and upload functionality.
Images

### CODE REVIEW

**Comment by tewarig** [comment]
@pkesavap please , review this  : )

**Comment by pkesavap** [comment]
Hey @tewarig  sorry for the delay had a busy week.

Could you raise the PR into prajith007007:encryption branch rather than the master?

**Comment by pkesavap** [comment]
Also i think its best to set a fixed screen size when we click on photos, rather than make the screen size accomodate the photo's size.
Because in the latter, the browser is getting large, as an effort to adapt to the picture.

**Comment by tewarig** [comment]
> Hey @tewarig sorry for the delay had a busy week.
> 
> Could you raise the PR into prajith007007:encryption branch rather than the master?

ohk, I will do that : )

**Comment by tewarig** [comment]
> Also i think its best to set a fixed screen size when we click on photos, rather than make the screen size accommodate the photo
> Because in the latter the current web page is becoming big, as an effort to adapt to the picture.

sorry, I didn't get this. but for implementing this image gallery, I am using the lightbox library. it will take care. the image would not overflow in any case.

**Comment by pkesavap** [comment]
bug

@tewarig ^^ See the blue line, that hinders in this gif.

This happens because of my screen size being big. I guess that needs to be handled properly?
We can discuss this over this weeks sync. Should be small fix .. :)

**Comment by tewarig** [comment]
> bug
> 
> @tewarig ^^ See the blue line, that hinders in this gif.
> 
> This happens because of my screen size being big. I guess that needs to be handled properly?
> We can discuss this over this weeks sync. Should be small fix .. :)

ohh got it this might be because I tried to add a custom scroll bar. i will remove them .

**Comment by tewarig** [comment]
> We can discuss this over this weeks sync. Should be small fix .. :)

I will close this or and raise a new pr on the another branch with the fix : )

**Pull request closed without merging**
